# Generated by Django 4.1.1 on 2022-12-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('purpose', models.CharField(blank=True, max_length=128, null=True)),
                ('bank', models.CharField(max_length=32)),
                ('accNumber', models.CharField(max_length=32)),
                ('branch', models.CharField(max_length=128)),
                ('routing', models.CharField(max_length=128)),
                ('telno', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holder', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('purpose', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('NotStarted', 'Not Started'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='NotStarted', max_length=10)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('raisedFund', models.IntegerField(null=True)),
                ('spentFund', models.IntegerField(null=True)),
                ('targetFund', models.IntegerField(null=True)),
                ('participants', models.IntegerField(default=0, null=True)),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name', max_length=64)),
                ('priority', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txType', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdraw'), ('INTEREST', 'Interest'), ('FEES', 'fees')], max_length=10)),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='transaction/%Y')),
                ('confirmed', models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed')], default='UnConfirmed', max_length=16)),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankaccount')),
                ('exType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.expensetype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Owner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canEdit', models.CharField(max_length=24)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='prjType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projecttype'),
        ),
        migrations.AddField(
            model_name='project',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.TextField(max_length=500)),
                ('discussion', models.TextField(max_length=2000)),
                ('resolution', models.TextField(max_length=1000)),
                ('todos', models.TextField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expensetype',
            name='prjType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.projecttype'),
        ),
        migrations.CreateModel(
            name='Commitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Past', 'Past')], default='Current', max_length=7)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitee_member', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
