# Generated by Django 4.1.1 on 2022-12-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=16)),
                ('school', models.CharField(max_length=32, null=True)),
                ('grade', models.CharField(max_length=16, null=True)),
                ('account', models.CharField(max_length=32)),
                ('bank', models.CharField(max_length=16)),
                ('branch', models.CharField(max_length=16)),
                ('accountHolder', models.CharField(max_length=32)),
                ('holderMobile', models.CharField(max_length=16, null=True)),
                ('parent', models.CharField(max_length=32, null=True)),
                ('principal', models.CharField(max_length=32, null=True)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('Edu-Student', 'Student'), ('Edu-Teacher', 'Teacher'), ('Medical', 'Medical'), ('DryFood', 'Dryfood'), ('Transport', 'Transport')], max_length=12)),
                ('parentMobile', models.CharField(max_length=16, null=True)),
                ('principalMobile', models.CharField(max_length=16, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='targetFund',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary'),
        ),
    ]
