# Generated by Django 4.1.1 on 2022-12-04 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_beneficiary_rename_targetfund_project_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='endDate',
            field=models.DateField(blank=-1, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='grade',
            field=models.CharField(blank=-1, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='holderMobile',
            field=models.CharField(blank=-1, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='mobile',
            field=models.CharField(blank=-1, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='parent',
            field=models.CharField(blank=-1, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='parentMobile',
            field=models.CharField(blank=-1, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='principal',
            field=models.CharField(blank=-1, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='principalMobile',
            field=models.CharField(blank=-1, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='remarks',
            field=models.CharField(blank=-1, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='school',
            field=models.CharField(blank=-1, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
