# Generated by Django 4.1.1 on 2022-12-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_beneficiary_enddate_alter_beneficiary_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary'),
        ),
    ]
