# Generated by Django 4.1.1 on 2022-12-11 14:49

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='recommender',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='sponsor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(blank=True, default=accounts.models.Transaction.get_default_beneficiary, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary'),
        ),
        migrations.DeleteModel(
            name='RoleEdit',
        ),
    ]
