# Generated by Django 4.1.1 on 2022-12-12 14:00

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_beneficiary_recommender_beneficiary_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(default=accounts.models.Transaction.get_default_beneficiary, on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary'),
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=2000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y')),
                ('link', models.URLField(blank=True, help_text='Optional: any link to share', null=True)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('dislikes', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.PositiveSmallIntegerField(default=0)),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
