# Generated by Django 4.1.1 on 2023-01-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_beneficiary_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Patient', 'Patient'), ('Poverty', 'Poverty')], max_length=12),
        ),
    ]
