# Generated by Django 5.2.12 on 2026-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_beneficiary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('LKR', 'Sri Lankan Rupee')], default='LKR', max_length=3),
        ),
    ]
