# Generated by Django 5.2.12 on 2026-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bankaccount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amountLocal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('LKR', 'Sri Lankan Rupee')], default='LKR', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='confirmed',
            field=models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed')], default='Unconfirmed', max_length=16),
        ),
    ]
