# Generated by Django 4.1.1 on 2023-01-09 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_beneficiary_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportByMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('amount', models.IntegerField()),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('exType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.expensetype')),
            ],
        ),
    ]
