# Generated by Django 4.1.1 on 2023-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbymonth',
            name='exType',
            field=models.CharField(max_length=32),
        ),
    ]
