# Generated by Django 4.1.1 on 2023-01-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportbymonth_extype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbymonth',
            name='month',
            field=models.CharField(max_length=8),
        ),
    ]
